server:
  port: 8888

spring:
  application:
    name: config-service

  cloud:
    config:
      server:
        git:
          uri: file:///Users/jeonghun/git-local-repo # Mac 기준
        # url: file:///C:/Users/abc/Downloads/git-local-repo # Windows 기준
        # uri: https://github.com/onethejay/spring-cloud-config    # remote git