server:
  port: 8888

spring:
  application:
    name: config-service

#  config:
 #   activate:
  #    on-profile: dev

  cloud:
    config:
      server:
        git:
          uri: file:///Users/jeonghun/Desktop/git-local-repo # Mac 기준
        # url: file:///C:/Users/abc/Downloads/git-local-repo # Windows 기준